version: "3"
services:
  app:
    container_name: app
    build: .
    ports:
      - "4000:4000"
    command: npm start
    volumes:
      - .:/usr/app
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./data:/redis/db
    ports:
      - "6379:6379"